"""Font-to-contact fitting extracted from the validated lab registration studies.

Stroke order is a template prior; registration and overlap ownership are inferred.
No experiment checkout, global character dictionary or image files are needed.
"""
import io
import cv2
import cairosvg
import numpy as np
from PIL import Image
from scipy import ndimage as ndi
from scipy.ndimage import gaussian_filter
from scipy.interpolate import PchipInterpolator
from skimage.registration import optical_flow_tvl1

S = 160
SIZE = 480


def template(d):
    n=len(d['strokes'])
    stack=[]
    for outline in d['strokes']:
        svg=f'<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><g transform="scale(.15625) translate(0 900) scale(1 -1)"><path d="{outline}"/></g></svg>'
        stack.append(np.asarray(Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svg.encode()))).convert('RGBA'))[:,:,3])
    stack=np.asarray(stack)
    union=stack.max(0)>128
    yy,xx=np.where(union);x0=xx.min();x1=xx.max()+1;y0=yy.min();y1=yy.max()+1
    scale=(S-20)/max(x1-x0,y1-y0)
    width=round((x1-x0)*scale);height=round((y1-y0)*scale)
    ox=(S-width)//2;oy=(S-height)//2
    layers=np.zeros((n,S,S),np.float32)
    progress=np.zeros_like(layers)
    yy,xx=np.mgrid[:S,:S]
    for i in range(n):
        layers[i,oy:oy+height,ox:ox+width]=cv2.resize(stack[i,y0:y1,x0:x1],(width,height))/255
        points=np.array(d['medians'][i],float)
        points[:,1]=900-points[:,1]
        points=points*.15625
        points=(points-[x0,y0])*scale+[ox,oy]
        ls=np.linalg.norm(np.diff(points,axis=0),axis=1)
        dist=np.full((S,S),1e9);offset=0
        for a,b,length in zip(points[:-1],points[1:],ls):
            v=b-a
            t=np.clip(((xx-a[0])*v[0]+(yy-a[1])*v[1])/max(length**2,1e-6),0,1)
            dd=(xx-a[0]-t*v[0])**2+(yy-a[1]-t*v[1])**2
            update=dd<dist
            progress[i][update]=(offset+t[update]*length)/max(ls.sum(),1)
            dist=np.minimum(dist,dd);offset+=length
    return layers,progress

def bbox(mask):
    y, x = np.where(mask)
    if not len(x):
        raise ValueError('Empty glyph or template')
    return x.min(), y.min(), x.max() + 1, y.max() + 1

def fit_template(layers, progress, ink):
    """Apply one shared anisotropic affine transform to masks AND progress."""
    sx0, sy0, sx1, sy1 = bbox(layers.max(0) > .5)
    tx0, ty0, tx1, ty1 = bbox(ink)
    yy, xx = np.mgrid[:S,:S]
    xs = (xx-tx0)*(sx1-sx0-1)/max(tx1-tx0-1,1) + sx0
    ys = (yy-ty0)*(sy1-sy0-1)/max(ty1-ty0-1,1) + sy0
    coords = np.array([ys,xs])
    fitted = np.stack([ndi.map_coordinates(a,coords,order=1,mode='constant') for a in layers])
    phase = np.stack([ndi.map_coordinates(a,coords,order=1,mode='nearest') for a in progress])
    return fitted, phase

def registered_fields(gray, glyph):
    layers, phase = template(glyph)
    target = (255-gray)/255.
    layers, phase = fit_template(layers, phase, gray < 150)
    flow = optical_flow_tvl1(ndi.gaussian_filter(target,1.5),
                            ndi.gaussian_filter(layers.max(0),1.5),
                            attachment=12,tightness=.3,num_warp=8,num_iter=12)
    yy,xx=np.mgrid[:S,:S]
    coords=np.array([yy+flow[0],xx+flow[1]])
    warped=np.stack([ndi.map_coordinates(a,coords,order=1,mode='constant') for a in layers])
    progress=np.stack([ndi.map_coordinates(a,coords,order=1,mode='nearest') for a in phase])
    return warped,progress

def ribbon_envelope(support, phase, shape):
    """Fit a smooth centerline/width ribbon; return envelope and arc progress.

    Progress bins maintain the ordered path through turns. Width is measured
    normal to the local tangent, then smoothed independently from the centerline.
    The final source ink is NOT blurred or regenerated by this function.
    """
    mask=support>.2
    yy,xx=np.where(mask)
    if not len(xx):
        raise ValueError('Cannot infer a completely missing template stroke')
    p=phase[mask];points=[];positions=[]
    lo,hi=np.quantile(p,[.005,.995])
    edges=np.linspace(lo,hi+1e-6,25)
    for a,b in zip(edges[:-1],edges[1:]):
        chosen=(p>=a)&(p<b)
        if chosen.sum()<2:continue
        points.append([np.mean(xx[chosen]),np.mean(yy[chosen])])
        positions.append((a+b)/2)
    h,w=shape
    if len(points)<3:
        # Degenerate dot/near-constant phase: retain its isolated envelope.
        return (cv2.resize(mask.astype(np.uint8),(w,h),interpolation=cv2.INTER_NEAREST)>0,
                np.clip(cv2.resize(phase,(w,h),interpolation=cv2.INTER_CUBIC),0,1))
    points=ndi.gaussian_filter1d(np.array(points),.9,axis=0)
    tangent=np.gradient(points,axis=0)
    tangent/=np.maximum(np.linalg.norm(tangent,axis=1,keepdims=True),1e-5)
    normals=np.stack([-tangent[:,1],tangent[:,0]],axis=1)
    radii=[]
    for point,normal,t in zip(points,normals,positions):
        chosen=abs(p-t)<max((hi-lo)/20,.025)
        offsets=(np.stack([xx[chosen],yy[chosen]],axis=1)-point)@normal
        radii.append(max(1,float(np.quantile(abs(offsets),.90))))
    radii=ndi.gaussian_filter1d(np.array(radii),1.5)
    parameter=np.linspace(0,len(points)-1,160)
    path=PchipInterpolator(np.arange(len(points)),points)(parameter)
    radius=PchipInterpolator(np.arange(len(points)),radii)(parameter)
    return rasterize_ribbon(path,radius,support.shape,shape)

def rasterize_ribbon(path, radius, source_shape, shape):
    """Rasterize a sampled centerline and radius using shared automatic/manual geometry."""
    h,w=shape
    tangent=np.gradient(path,axis=0)
    tangent/=np.maximum(np.linalg.norm(tangent,axis=1,keepdims=True),1e-5)
    normal=np.stack([-tangent[:,1],tangent[:,0]],axis=1)
    polygon=np.concatenate([path+normal*radius[:,None],(path-normal*radius[:,None])[::-1]])
    scale=np.array([w/source_shape[1],h/source_shape[0]])
    envelope=np.zeros((h,w),np.uint8)
    cv2.fillPoly(envelope,[np.round(polygon*scale).astype(np.int32)],1)
    for point,rad in [(path[0],radius[0]),(path[-1],radius[-1])]:
        cv2.ellipse(envelope,tuple(np.round(point*scale).astype(int)),
                    tuple(np.maximum(1,np.round(rad*scale)).astype(int)),0,0,360,1,-1)
    # Stable arc-length progress on the new centerline, extended over its width.
    path=path*scale
    lengths=np.r_[0,np.cumsum(np.linalg.norm(np.diff(path,axis=0),axis=1))]
    times=lengths/max(lengths[-1],1e-6)
    seeds=np.zeros((h,w),np.uint8);values=np.zeros((h,w),np.float32)
    for a,b,ta,tb in zip(path[:-1],path[1:],times[:-1],times[1:]):
        start=tuple(np.round(a).astype(int));end=tuple(np.round(b).astype(int))
        cv2.line(seeds,start,end,1,1)
        cv2.line(values,start,end,float((ta+tb)/2),1)
    if not seeds.any():raise ValueError('Ribbon centerline lies outside target')
    nearest=ndi.distance_transform_edt(seeds==0,return_distances=False,return_indices=True)
    progress=ndi.gaussian_filter(values[tuple(nearest)],.8)
    return envelope.astype(bool),np.clip(progress,0,1)

def smooth_decomposition(warped, progress, target, sigma=.7, feather=.65):
    """Return source-colored stroke layers and smooth per-layer progress.

    Smooth centerline/width ribbons replace jagged registration boundaries. Log-sigmoid
    affinities make overlapping soft masks. Dividing by the strongest affinity
    gives at least one full-strength layer at EVERY source pixel. Far-away
    affinities below 1/255 are zeroed; the winning layer is always preserved.
    Thus max(layers)==target, including unsupported source ink, at every pixel.
    This coverage constraint does not establish correct semantic ownership.
    """
    if warped.ndim!=3 or progress.shape!=warped.shape or target.ndim!=2:
        raise ValueError('Expected [stroke,y,x] fields and a 2D target')
    if sigma<0 or feather<=0 or not np.isfinite(warped).all() or not np.isfinite(progress).all():
        raise ValueError('Invalid fields or smoothing parameters')
    if not np.isfinite(target).all() or np.any((target<0)|(target>1)):
        raise ValueError('Target must contain finite ink intensities in [0,1]')
    h,w=target.shape
    scores=[];phases=[]
    for support,phase in zip(warped,progress):
        mask,ribbon_phase=ribbon_envelope(support,phase,target.shape)
        distance=ndi.distance_transform_edt(mask)-ndi.distance_transform_edt(~mask)
        distance=ndi.gaussian_filter(distance,sigma)
        scores.append(-np.logaddexp(0,-distance/feather))
        phases.append(ribbon_phase)
    scores=np.array(scores,dtype=np.float32)
    alpha=np.exp(scores-scores.max(0))
    alpha[alpha<1/255]=0
    layers=alpha*target[None]
    return layers.astype(np.float32),np.array(phases,dtype=np.float32),alpha

def resample(points,n=100):
 p=np.asarray(points,float);t=np.r_[0,np.cumsum(np.linalg.norm(np.diff(p,axis=0),axis=1))]
 keep=np.r_[True,np.diff(t)>1e-8];t,p=t[keep],p[keep]
 return np.column_stack([np.interp(np.linspace(0,t[-1],n),t,p[:,j]) for j in range(2)])

def simplify_pairs(p,tol=.7):
 flat=p.reshape(len(p),4)
 def split(a,b):
  if b-a<2:return [a,b]
  v=flat[b]-flat[a];u=np.clip((flat[a+1:b]-flat[a])@v/max(v@v,1e-8),0,1)
  d=np.linalg.norm(flat[a+1:b]-flat[a]-u[:,None]*v,axis=1);k=a+1+d.argmax()
  if d.max()<=tol:return [a,b]
  return split(a,k)[:-1]+split(k,b)
 indices=split(0,len(p)-1)
 # RDP may reduce a small straight component to just its endpoints. Contact
 # interpolation needs at least three stations; retain an original interior
 # pair instead of dropping the component or inventing new boundary geometry.
 if len(indices)<3 and len(p)>=3:
  indices=[0,len(p)//2,len(p)-1]
 return p[indices]

def contacts_from_layer(layer,guide,name):
 mask=np.uint8(gaussian_filter(layer,.65)>.45)
 contours,_=cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
 if not contours:raise ValueError('Empty stroke '+name)
 contour=max(contours,key=cv2.contourArea)[:,0].astype(float)
 g=np.asarray(guide);ia=np.argmin(np.linalg.norm(contour-g[0],axis=1));ib=np.argmin(np.linalg.norm(contour-g[-1],axis=1))
 if ia==ib:ib=np.argmax(np.linalg.norm(contour-contour[ia],axis=1))
 contour=np.roll(contour,-ia,axis=0);ib=(ib-ia)%len(contour)
 a=resample(contour[:ib+1]);b=resample(np.vstack([contour[0],contour[:ib-1:-1]]))
 # Monotonic correspondence between two contour rails. Short cross-sections
 # avoid diagonal bridges across inside corners; guide progress stabilizes hooks.
 pa=np.argmin(((a[:,None]-g[None])**2).sum(2),axis=1)/max(len(g)-1,1)
 pb=np.argmin(((b[:,None]-g[None])**2).sum(2),axis=1)/max(len(g)-1,1)
 cost=((a[:,None]-b[None])**2).sum(2)+2500*(pa[:,None]-pb[None])**2
 n,m=cost.shape;dp=np.full((n,m),np.inf);prev=np.zeros((n,m),np.uint8);dp[0,0]=0
 for i in range(n):
  for j in range(m):
   if i==j==0:continue
   choices=[dp[i-1,j-1] if i and j else np.inf,dp[i-1,j] if i else np.inf,dp[i,j-1] if j else np.inf]
   k=int(np.argmin(choices));dp[i,j]=cost[i,j]+choices[k];prev[i,j]=k
 i,j=n-1,m-1;p=[]
 while True:
  p.append([a[i],b[j]])
  if i==j==0:break
  k=prev[i,j]
  if k in (0,1):i-=1
  if k in (0,2):j-=1
 pairs=simplify_pairs(np.asarray(p[::-1]));centers=pairs.mean(1)
 turns=np.zeros(len(pairs));v=np.diff(centers,axis=0);v/=np.maximum(np.linalg.norm(v,axis=1,keepdims=True),1e-5)
 turns[1:-1]=np.arccos(np.clip((v[:-1]*v[1:]).sum(1),-1,1))
 corners=np.where(turns>1.)[0].tolist()
 return dict(name=name,contacts=pairs.tolist(),corners=corners,tension=.5,
  features=[dict(station=1,kind='entry-press')]+[dict(station=k,kind='square-fold') for k in corners]+[dict(station=len(pairs)-2,kind='lift')])

def ordered_guide(layer,phase):
 yy,xx=np.where(layer>.25);weights=layer[yy,xx];p=phase[yy,xx]
 lo,hi=np.quantile(p,[.005,.995]);points=[]
 for a,b in zip(np.linspace(lo,hi+1e-5,25)[:-1],np.linspace(lo,hi+1e-5,25)[1:]):
  sel=(p>=a)&(p<b)
  if sel.sum():points.append(np.average(np.column_stack([xx[sel],yy[sel]]),axis=0,weights=weights[sel]))
 if len(points)<2:
  raise ValueError('Cannot infer ordered guide for degenerate stroke')
 return np.asarray(points)

def iou(a,b):
 a,b=a>.5,b>.5;return float((a&b).sum()/max((a|b).sum(),1))
